fmt:
    cargo fmt --all -- --check

clippy:
    cargo clippy --locked --all-targets --all-features -- -D warnings

test:
    cargo nextest run --locked

todo:
    cargo todo

check: fmt clippy test todo
