default_install_hook_types = ["pre-commit", "pre-push"]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "fmt"
name = "cargo fmt"
language = "system"
entry = "cargo fmt --all -- --check"
files = "(\\.rs$|(^|/)Cargo\\.(toml|lock)$)"
pass_filenames = false
stages = ["pre-commit"]

[[repos.hooks]]
id = "check"
name = "cargo check"
language = "system"
entry = "cargo check --locked --all-targets --all-features"
files = "(\\.rs$|(^|/)Cargo\\.(toml|lock)$)"
pass_filenames = false
stages = ["pre-commit"]

[[repos.hooks]]
id = "cargo-todo"
name = "cargo todo"
language = "system"
entry = "cargo todo"
files = "(\\.rs$|(^|/)Cargo\\.toml$)"
pass_filenames = false
stages = ["pre-commit"]

[[repos.hooks]]
id = "clippy"
name = "cargo clippy"
language = "system"
entry = "cargo clippy --locked --all-targets --all-features -- -D warnings"
pass_filenames = false
always_run = true
stages = ["pre-push"]

[[repos.hooks]]
id = "test"
name = "cargo test"
language = "system"
entry = "cargo test --locked"
pass_filenames = false
always_run = true
stages = ["pre-push"]
